package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, March 16, 2020 10:03:51 PM IST
*/

public interface HelloOperations 
{
  String sayHello (int a, int b);
  void shutdown ();
} // interface HelloOperations
